motors_node:
  ros__parameters:
    LEFT_DIR_PIN_NUM : 17
    LEFT_PWM_PIN_NUM : 18
    RIGHT_DIR_PIN_NUM : 23
    RIGHT_PWM_PIN_NUM : 24
    LEFT_MOTOR_SCALE : 0.96
    RIGHT_MOTOR_SCALE : 1.0
    WHEEL_BASE : 0.3
    MAX_SPEED : 0.5

encoder_node:
  ros__parameters:
    LEFT_ENCODER_PIN_NUM: 25
    RIGHT_ENCODER_PIN_NUM: 27
    MAGNET_COUNT : 6
    MODE : "Normal" # [Normal - Calibration] 

imu_node:
  ros__parameters:
    I2C_BUS_CHANNEL : 1
    IMU_REGISTER_ADDRESS : 0x69
    FREQUENCY : 50 # Hz