motors_node:
  ros__parameters:
    LEFT_DIR_PIN_NUM : 17
    LEFT_PWM_PIN_NUM : 18
    RIGHT_DIR_PIN_NUM : 23
    RIGHT_PWM_PIN_NUM : 24
    LEFT_MOTOR_SCALE : 1.0
    RIGHT_MOTOR_SCALE : 1.0
    WHEEL_BASE : 0.3
    MAX_SPEED : 1.0